### ISSUE TITLE
[Self-Host] protocol of next url is rewritten to https

### ISSUE THREAD

**Issue by an-tex** [mendableai/firecrawl#2275]
**Describe the Issue**
we deploy firecrawl in a Kubernetes cluster only reachable from within the cluster. hence there's no load balancer with ssl termination, just a simple http Kubernetes service. when querying for the results of a crawl, e.g. 
`http://api.firecrawl.svc:3002/v2/crawl/ID`, the url for the next page is `https://api.firecrawl.svc:3002/v2/crawl/ID?...`

hence the protocol is rewritten from http to https. if the firecrawl api should be reachable externally through a LoadBalancer I'd expect the LB to do any protocol related redirects. firecrawl it self should stick to the requested protocol.

the rewrite happens in https://github.com/firecrawl/firecrawl/blob/main/apps/api/src/controllers/v2/crawl-status.ts#L409

**Environment (please complete the following information):**
- OS: linux / kubernetes
- Firecrawl Version: 2.3.0

**Comment by abimaelmartell** [comment]
hi @an-tex, can you set your `ENV` env variable to `local`? That should keep your original protocol

**Comment by an-tex** [comment]
hi @abimaelmartell thanks for your answer. it would, but it seems to me this ENV is used in a few other places too. wouldn't it have unwanted side effects? this is a production environment after all

**Comment by mogery** [comment]
Fixed by 8c709b8ec

**Comment by an-tex** [comment]
@mogery I'm still seeing this (currently latest image tag). it seems a following (unrelated) commit reverted the changes again https://github.com/firecrawl/firecrawl/commit/186335ebb7d0ea2f3cdef7d449f702d0332e70f0

**Comment by mogery** [comment]
> [@mogery](https://github.com/mogery) I'm still seeing this (currently latest image tag). it seems a following (unrelated) commit reverted the changes again [186335e](https://github.com/firecrawl/firecrawl/commit/186335ebb7d0ea2f3cdef7d449f702d0332e70f0)

Apologies, fixed in 45b498ddd1837057607fa7b6d0d34f36788b6131
