### ISSUE TITLE
[BUG] Firecrawl can't see local redis instance

### ISSUE THREAD

**Issue by WarpWing** [mendableai/firecrawl#428]
Hi all,

I'm trying to self host Firecrawl but I can't see to make Firecrawl see the Redis instance

![image](https://github.com/user-attachments/assets/0be62718-2d2e-40c8-902a-b0c6fe51e3d6)
![image](https://github.com/user-attachments/assets/d62e3292-6704-4a6c-a671-38c7c53f5240)

I've tried changing it to the actual ip of the host but it keeps trying to connect to 127.0.0.1, any ideas?

**Comment by nagendrakumar02** [comment]
I had a similar issue, I fixed it by creating a network to host redis

docker network create my-network
docker run -d --name my-redis-stack --network my-network -p 6379:6379 redis/redis-stack-server:latest

and in your .env use 
REDIS_URL=redis://localhost:6379

**Comment by nickscamara** [comment]
I believe we forgot to add to the .env.example the new Redis variable for the rate limits. Just edited the .env.local and .env.example to reflect the change we did yesterday. Let me know if this fixes it.

**Comment by WarpWing** [comment]
> I believe we forgot to add to the .env.example the new Redis variable for the rate limits. Just edited the .env.local and .env.example to reflect the change we did yesterday. Let me know if this fixes it.

So I still tried to launch it but I still get the same error
![image](https://github.com/user-attachments/assets/82a84ac1-dabb-4e8f-bb6a-cb52d9e1ac14)

Here is the config file:
![image](https://github.com/user-attachments/assets/64abc55c-5de3-48e9-b850-e8acfbcde5b2)

I'm suspecting the env variables are not updating. I noticed if I put a custom redis connection string that it's still using 127.0.0.1. Perhaps that could be it?

**Comment by laura-y7860** [comment]
I added `REDIS_RATE_LIMIT_URL=${REDIS_RATE_LIMIT_URL} ` as an environment in docker compose file and the error seems to dissapear, haven't tried if it actually work or not tho

**Comment by WarpWing** [comment]
> REDIS_RATE_LIMIT_URL=${REDIS_RATE_LIMIT_URL}

That lines up with the fixes that @nickscamara pushed. 
![image](https://github.com/user-attachments/assets/0fc8258b-33db-4e63-a0cd-b49ad1f30fb7)


Just tried it, still nada.
![image](https://github.com/user-attachments/assets/c4ed8aa9-0e70-40e1-8970-b39a503a90fb)

**Comment by laura-y7860** [comment]
make sure REDIS_URL and REDIS_RATE_LIMIT_URL switched to` redis://redis:6379` and see if the bug still happens

**Comment by WarpWing** [comment]
> make sure REDIS_URL and REDIS_RATE_LIMIT_URL switched to` redis://redis:6379` and see if the bug still happens

Ah, that fixed it! Thanks a lot!

**Comment by nickscamara** [comment]
Just added to the docker compose as well. Thank you everyone!
