### ISSUE TITLE
[Self-Host] Unable to build the docker image

### ISSUE THREAD

**Issue by saidharanidhar** [mendableai/firecrawl#948]
**Describe the Issue**
Followed self host instructions. Not able to progress beyond `docker-compose build` step.

**To Reproduce**
Steps to reproduce the issue:
1. Clone the repo and checkout to the main branch.
2. Follow self hosting instructions.

**Expected Behavior**
It should pass the build.

**Screenshots**
```
➜  firecrawl git:(main) docker-compose build --no-cache
WARN[0000] The "LOGTAIL_KEY" variable is not set. Defaulting to a blank string.
WARN[0000] The "OPENAI_BASE_URL" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOGTAIL_KEY" variable is not set. Defaulting to a blank string.
WARN[0000] The "OPENAI_BASE_URL" variable is not set. Defaulting to a blank string.
[+] Building 85.8s (25/32)                                                                                                                                                docker:desktop-linuxx
 => [playwright-service internal] load build definition from Dockerfile                                                                                                                   0.0ss
 => => transferring dockerfile: 1.20kB                                                                                                                                                    0.0ss
 => [playwright-service internal] load .dockerignore                                                                                                                                      0.0ss
 => => transferring context: 2B                                                                                                                                                           0.0ss
 => [playwright-service internal] load metadata for docker.io/library/python:3.11-slim                                                                                                    1.9ss
 => CACHED [playwright-service 1/6] FROM docker.io/library/python:3.11-slim@sha256:370c586a6ffc8c619e6d652f81c094b34b14b8f2fb9251f092de23f16e299b78                                       0.0ss
 => [playwright-service internal] load build context                                                                                                                                      0.0ss
 => => transferring context: 538B                                                                                                                                                         0.0ss
 => [playwright-service 2/6] RUN apt-get update && apt-get install -y --no-install-recommends     gcc     libstdc++6                                                                      7.5ss
 => [playwright-service 3/6] WORKDIR /app                                                                                                                                                 0.0ss
 => [playwright-service 4/6] COPY requirements.txt ./                                                                                                                                     0.0ss
 => [playwright-service 5/6] RUN pip install --no-cache-dir --upgrade -r requirements.txt &&     pip uninstall -y py &&     playwright install chromium && playwright install-deps chro  56.1ss
 => [playwright-service 6/6] COPY . ./                                                                                                                                                    0.0s
 => [playwright-service] exporting to image                                                                                                                                               3.2s
 => => exporting layers                                                                                                                                                                   3.2s
 => => writing image sha256:40f4dbb2b5dbe204f7bc72222263af6f1bfb3e4e0aeeec50a443f1cc43eabfbb                                                                                              0.0s
 => => naming to docker.io/library/firecrawl-playwright-service                                                                                                                           0.0s
 => [api internal] load .dockerignore                                                                                                                                                     0.0s
 => => transferring context: 110B                                                                                                                                                         0.0s
 => [api internal] load build definition from Dockerfile                                                                                                                                  0.0s
 => => transferring dockerfile: 1.58kB                                                                                                                                                    0.0s
 => [api internal] load metadata for docker.io/library/node:20-slim                                                                                                                       1.9s
 => [api internal] load metadata for docker.io/library/golang:1.19                                                                                                                        1.9s
 => CACHED [api base 1/4] FROM docker.io/library/node:20-slim@sha256:f44fa8d6d0ef15fe252459ac5d3d178362231a7948d7d07e147bae891006e2e5                                                     0.0s
 => [api internal] load build context                                                                                                                                                     0.0s
 => => transferring context: 18.66kB                                                                                                                                                      0.0s
 => CACHED [api go-base 1/3] FROM docker.io/library/golang:1.19@sha256:3025bf670b8363ec9f1b4c4f27348e6d9b7fec607c47e401e40df816853e743a                                                   0.0s
 => [api base 2/4] RUN corepack enable                                                                                                                                                    0.4s
 => [api go-base 2/3] COPY sharedLibs/go-html-to-md /app/sharedLibs/go-html-to-md                                                                                                         0.0s
 => CANCELED [api go-base 3/3] RUN cd /app/sharedLibs/go-html-to-md &&     go mod tidy &&     go build -o html-to-markdown.so -buildmode=c-shared html-to-markdown.go &&     chmod +x h  14.2s
 => [api base 3/4] COPY . /app                                                                                                                                                            0.0s
 => [api base 4/4] WORKDIR /app                                                                                                                                                           0.0s
 => CANCELED [api build 1/4] RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile                                                                            13.5s
 => ERROR [api prod-deps 1/1] RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --prod --frozen-lockfile                                                                     9.4s
------
 > [api prod-deps 1/1] RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --prod --frozen-lockfile:
0.416 ! Corepack is about to download https://registry.npmjs.org/pnpm/-/pnpm-9.15.0.tgz
1.174 ! The local project doesn't define a 'packageManager' field. Corepack will now add one referencing pnpm@9.15.0+sha512.76e2379760a4328ec4415815bcd6628dee727af3779aaa4c914e3944156c4299921a89f976381ee107d41f12cfa4b66681ca9c718f0668fa0831ed4c6d8ba56c.
1.175 ! For more details about this field, consult the documentation at https://nodejs.org/api/packages.html#packagemanager
1.175
1.605 Lockfile is up to date, resolution step is skipped
1.668 Progress: resolved 1, reused 0, downloaded 0, added 0
1.937 Packages: +739
1.937 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
2.687 Progress: resolved 739, reused 0, downloaded 82, added 79
3.683 Progress: resolved 739, reused 0, downloaded 146, added 146
4.697 Progress: resolved 739, reused 0, downloaded 226, added 221
5.726 Progress: resolved 739, reused 0, downloaded 291, added 288
7.043 Progress: resolved 739, reused 0, downloaded 317, added 305
8.147 Progress: resolved 739, reused 0, downloaded 319, added 312
8.909 Killed
------
failed to solve: process "/bin/sh -c pnpm install --prod --frozen-lockfile" did not complete successfully: exit code: 137
```

**Environment (please complete the following information):**
- OS: macOS (m1)
- Firecrawl Version: checked on main branch and v1.0.0 tag. 
- Node.js Version: Don't know.
- Docker Version (if applicable): `Docker version 24.0.7, build afdd53b`
- Database Type and Version: Don't know.

**Configuration**
Defaults.

**Comment by Eternity714** [comment]
i think i fixed it after i changed the npm registry

**Comment by saidharanidhar** [comment]
I pulled the latest code from main and it's still failing. The same error. Anything I have to change?

**Comment by alex14dark** [comment]
Could it be that your machine is running out of memory?

**Comment by Eternity714** [comment]
> I pulled the latest code from main and it's still failing. The same error. Anything I have to change?

I modify the Dockerfile and add COREPACK_NPM_REGISTRY to Dockerfile‘s environment variables

**Comment by saidharanidhar** [comment]
Okay! It made some progress.
Here is the latest error.

` > [api prod-deps 1/1] RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --prod --frozen-lockfile:
0.582 ! Corepack is about to download https://registry.npmjs.org/pnpm/-/pnpm-9.15.0.tgz
1.215 ! The local project doesn't define a 'packageManager' field. Corepack will now add one referencing pnpm@9.15.0+sha512.76e2379760a4328ec4415815bcd6628dee727af3779aaa4c914e3944156c4299921a89f976381ee107d41f12cfa4b66681ca9c718f0668fa0831ed4c6d8ba56c.
1.215 ! For more details about this field, consult the documentation at https://nodejs.org/api/packages.html#packagemanager
1.215 
1.598 Lockfile is up to date, resolution step is skipped
1.658 Progress: resolved 1, reused 0, downloaded 0, added 0
1.776 Packages: +775
1.776 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
2.660 Progress: resolved 775, reused 526, downloaded 0, added 0
3.692 Progress: resolved 775, reused 650, downloaded 0, added 190
4.711 Progress: resolved 775, reused 650, downloaded 0, added 376
5.739 Progress: resolved 775, reused 650, downloaded 0, added 479
6.789 Progress: resolved 775, reused 650, downloaded 0, added 562
7.832 Progress: resolved 775, reused 650, downloaded 13, added 647
14.31 Progress: resolved 775, reused 650, downloaded 13, added 649
15.43 Progress: resolved 775, reused 650, downloaded 29, added 676
39.82 Progress: resolved 775, reused 650, downloaded 41, added 686
42.63 Progress: resolved 775, reused 650, downloaded 72, added 716
43.70 Progress: resolved 775, reused 650, downloaded 74, added 720
49.33 Progress: resolved 775, reused 650, downloaded 80, added 723
109.4 Progress: resolved 775, reused 650, downloaded 84, added 725
120.4 Progress: resolved 775, reused 650, downloaded 88, added 733
121.4 Progress: resolved 775, reused 650, downloaded 121, added 769
122.4 Progress: resolved 775, reused 650, downloaded 124, added 774
122.5 Progress: resolved 775, reused 650, downloaded 125, added 775, done
123.3 .../.pnpm/koffi@2.9.0/node_modules/koffi install$ node src/cnoke/cnoke.js -p . -d src/koffi --prebuild
123.3 .../canvas@2.11.2/node_modules/canvas install$ node-pre-gyp install --fallback-to-build --update-binary
123.3 .../node_modules/msgpackr-extract install$ node-gyp-build-optional-packages
123.3 .../node_modules/@sentry/cli postinstall$ node ./scripts/install.js
123.4 .../node_modules/@sentry/profiling-node install$ node scripts/check-build.js
127.0 .../node_modules/@sentry/profiling-node install: @sentry/profiling-node: Precompiled binary found, attempting to load /app/node_modules/.pnpm/@sentry+profiling-node@8.26.0/node_modules/@sentry/profiling-node/lib/sentry_cpu_profiler-linux-arm64-glibc-115.node
127.1 .../node_modules/@sentry/profiling-node install: @sentry/profiling-node: Precompiled binary found, skipping build from source.
127.1 .../node_modules/msgpackr-extract install: node:internal/errors:541
127.1 .../node_modules/msgpackr-extract install:       throw error;
127.1 .../node_modules/msgpackr-extract install:       ^
127.1 .../node_modules/msgpackr-extract install: TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined
127.1 .../node_modules/msgpackr-extract install:     at Module.require (node:internal/modules/cjs/loader:1304:3)
127.1 .../node_modules/msgpackr-extract install:     at require (node:internal/modules/helpers:179:18)
127.1 .../node_modules/msgpackr-extract install:     at load (/app/node_modules/.pnpm/node-gyp-build-optional-packages@5.2.2/node_modules/node-gyp-build-optional-packages/node-gyp-build.js:28:10)
127.1 .../node_modules/msgpackr-extract install:     at Object.<anonymous> (/app/node_modules/.pnpm/node-gyp-build-optional-packages@5.2.2/node_modules/node-gyp-build-optional-packages/build-test.js:19:19)
127.1 .../node_modules/msgpackr-extract install:     at Module._compile (node:internal/modules/cjs/loader:1469:14)
127.1 .../node_modules/msgpackr-extract install:     at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
127.1 .../node_modules/msgpackr-extract install:     at Module.load (node:internal/modules/cjs/loader:1288:32)
127.1 .../node_modules/msgpackr-extract install:     at Module._load (node:internal/modules/cjs/loader:1104:12)
127.1 .../node_modules/msgpackr-extract install:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:173:12)
127.1 .../node_modules/msgpackr-extract install:     at node:internal/main/run_main_module:28:49 {
127.1 .../node_modules/msgpackr-extract install:   code: 'ERR_INVALID_ARG_TYPE'
127.1 .../node_modules/msgpackr-extract install: }
127.1 .../node_modules/msgpackr-extract install: Node.js v20.18.1
127.1 .../node_modules/msgpackr-extract install: The failure above indicates the primary issue with the native builds which are included for all major platforms. Will now attempt to build the package locally in case this can be resolved by re-compiling.
127.2 .../node_modules/@sentry/profiling-node install: Done
127.2 .../node_modules/@sentry/cli postinstall: Done
127.2 .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp info it worked if it ends with ok
127.2 .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp info using node-pre-gyp@1.0.11
127.2 .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp info using node@20.18.1 | linux | arm64
127.2 .../.pnpm/koffi@2.9.0/node_modules/koffi install: Done
127.5 .../node_modules/puppeteer postinstall$ node install.mjs
135.9 .../wordpos@2.1.0/node_modules/wordpos postinstall$ node tools/stat.js --no-stats index.adv index.adj index.verb index.noun
136.3 .../node_modules/msgpackr-extract install: gyp info it worked if it ends with ok
136.4 .../node_modules/msgpackr-extract install: gyp info using node-gyp@10.2.0
136.4 .../node_modules/msgpackr-extract install: gyp info using node@20.18.1 | linux | arm64
137.3 .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v115-linux-glibc-arm64.tar.gz
138.9 .../wordpos@2.1.0/node_modules/wordpos postinstall: DB folder:  /app/node_modules/.pnpm/wordnet-db@3.1.14/node_modules/wordnet-db/dict
140.2 .../node_modules/msgpackr-extract install: gyp ERR! find Python 
140.4 .../node_modules/msgpackr-extract install: gyp ERR! find Python Python is not set from command line or npm configuration
140.5 .../node_modules/msgpackr-extract install: gyp ERR! find Python Python is not set from environment variable PYTHON
140.6 .../node_modules/msgpackr-extract install: gyp ERR! find Python checking if "python3" can be used
140.7 .../node_modules/msgpackr-extract install: gyp ERR! find Python - executable path is ""
140.8 .../node_modules/msgpackr-extract install: gyp ERR! find Python - "" could not be run
141.0 .../node_modules/msgpackr-extract install: gyp ERR! find Python checking if "python" can be used
141.1 .../node_modules/msgpackr-extract install: gyp ERR! find Python - executable path is ""
141.2 .../node_modules/msgpackr-extract install: gyp ERR! find Python - "" could not be run
141.3 .../node_modules/msgpackr-extract install: gyp ERR! find Python 
141.4 .../node_modules/msgpackr-extract install: gyp ERR! find Python **********************************************************
141.4 .../node_modules/msgpackr-extract install: gyp ERR! find Python You need to install the latest version of Python.
141.4 .../node_modules/msgpackr-extract install: gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
141.4 .../node_modules/msgpackr-extract install: gyp ERR! find Python you can try one of the following options:
141.4 .../node_modules/msgpackr-extract install: gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
141.4 .../node_modules/msgpackr-extract install: gyp ERR! find Python (accepted by both node-gyp and npm)
141.4 .../node_modules/msgpackr-extract install: gyp ERR! find Python - Set the environment variable PYTHON
141.4 .../node_modules/msgpackr-extract install: gyp ERR! find Python - Set the npm configuration variable python:
141.4 .../node_modules/msgpackr-extract install: gyp ERR! find Python npm config set python "/path/to/pythonexecutable"
141.4 .../node_modules/msgpackr-extract install: gyp ERR! find Python For more information consult the documentation at:
141.4 .../node_modules/msgpackr-extract install: gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
141.4 .../node_modules/msgpackr-extract install: gyp ERR! find Python **********************************************************
141.4 .../node_modules/msgpackr-extract install: gyp ERR! find Python 
141.4 .../node_modules/msgpackr-extract install: gyp ERR! configure error 
141.4 .../node_modules/msgpackr-extract install: gyp ERR! stack Error: Could not find any Python installation to use
141.4 .../node_modules/msgpackr-extract install: gyp ERR! stack at PythonFinder.fail (/root/.cache/node/corepack/v1/pnpm/9.15.0/dist/node_modules/node-gyp/lib/find-python.js:306:11)
141.4 .../node_modules/msgpackr-extract install: gyp ERR! stack at PythonFinder.findPython (/root/.cache/node/corepack/v1/pnpm/9.15.0/dist/node_modules/node-gyp/lib/find-python.js:164:17)
141.4 .../node_modules/msgpackr-extract install: gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
141.4 .../node_modules/msgpackr-extract install: gyp ERR! stack at async configure (/root/.cache/node/corepack/v1/pnpm/9.15.0/dist/node_modules/node-gyp/lib/configure.js:27:18)
141.4 .../node_modules/msgpackr-extract install: gyp ERR! stack at async run (/root/.cache/node/corepack/v1/pnpm/9.15.0/dist/node_modules/node-gyp/bin/node-gyp.js:81:18)
141.4 .../node_modules/msgpackr-extract install: gyp ERR! System Linux 6.5.11-linuxkit
141.4 .../node_modules/msgpackr-extract install: gyp ERR! command "/usr/local/bin/node" "/root/.cache/node/corepack/v1/pnpm/9.15.0/dist/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
141.4 .../node_modules/msgpackr-extract install: gyp ERR! cwd /app/node_modules/.pnpm/msgpackr-extract@3.0.3/node_modules/msgpackr-extract
141.4 .../node_modules/msgpackr-extract install: gyp ERR! node -v v20.18.1
141.4 .../node_modules/msgpackr-extract install: gyp ERR! node-gyp -v v10.2.0
141.4 .../node_modules/msgpackr-extract install: gyp ERR! not ok 
141.4 .../node_modules/msgpackr-extract install: Failed
141.9 .../wordpos@2.1.0/node_modules/wordpos postinstall: index.adv buckets 1172, max 125 at in_, sum 4475, avg 3.82, median 2
142.0 .../wordpos@2.1.0/node_modules/wordpos postinstall:   wrote /app/node_modules/.pnpm/wordnet-db@3.1.14/node_modules/wordnet-db/dict/fast-index.adv.json
142.6 .../wordpos@2.1.0/node_modules/wordpos postinstall: index.verb buckets 1623, max 176 at dis, sum 11540, avg 7.11, median 3
142.6 .../wordpos@2.1.0/node_modules/wordpos postinstall:   wrote /app/node_modules/.pnpm/wordnet-db@3.1.14/node_modules/wordnet-db/dict/fast-index.verb.json
143.6 .../wordpos@2.1.0/node_modules/wordpos postinstall: index.adj buckets 2326, max 310 at non, sum 21499, avg 9.24, median 3
144.0 .../wordpos@2.1.0/node_modules/wordpos postinstall:   wrote /app/node_modules/.pnpm/wordnet-db@3.1.14/node_modules/wordnet-db/dict/fast-index.adj.json
149.1 .../wordpos@2.1.0/node_modules/wordpos postinstall: index.noun buckets 4527, max 3859 at gen, sum 117953, avg 26.06, median 4
149.3 .../wordpos@2.1.0/node_modules/wordpos postinstall:   wrote /app/node_modules/.pnpm/wordnet-db@3.1.14/node_modules/wordnet-db/dict/fast-index.noun.json
149.5 .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v115-linux-glibc-arm64.tar.gz 
149.5 .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@20.18.1 (node-v115 ABI, glibc) (falling back to source compile with node-gyp) 
149.5 .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v115-linux-glibc-arm64.tar.gz 
149.5 .../wordpos@2.1.0/node_modules/wordpos postinstall: Done
149.6 .../canvas@2.11.2/node_modules/canvas install: gyp info it worked if it ends with ok
149.6 .../canvas@2.11.2/node_modules/canvas install: gyp info using node-gyp@10.2.0
149.6 .../canvas@2.11.2/node_modules/canvas install: gyp info using node@20.18.1 | linux | arm64
149.6 .../canvas@2.11.2/node_modules/canvas install: gyp info ok 
149.8 .../canvas@2.11.2/node_modules/canvas install: gyp info it worked if it ends with ok
149.8 .../canvas@2.11.2/node_modules/canvas install: gyp info using node-gyp@10.2.0
149.8 .../canvas@2.11.2/node_modules/canvas install: gyp info using node@20.18.1 | linux | arm64
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! find Python 
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! find Python Python is not set from command line or npm configuration
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! find Python Python is not set from environment variable PYTHON
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! find Python checking if "python3" can be used
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! find Python - executable path is ""
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! find Python - "" could not be run
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! find Python checking if "python" can be used
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! find Python - executable path is ""
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! find Python - "" could not be run
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! find Python 
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! find Python **********************************************************
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! find Python You need to install the latest version of Python.
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! find Python you can try one of the following options:
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! find Python (accepted by both node-gyp and npm)
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! find Python - Set the environment variable PYTHON
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! find Python - Set the npm configuration variable python:
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! find Python npm config set python "/path/to/pythonexecutable"
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! find Python For more information consult the documentation at:
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! find Python **********************************************************
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! find Python 
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! configure error 
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! stack Error: Could not find any Python installation to use
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! stack at PythonFinder.fail (/root/.cache/node/corepack/v1/pnpm/9.15.0/dist/node_modules/node-gyp/lib/find-python.js:306:11)
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! stack at PythonFinder.findPython (/root/.cache/node/corepack/v1/pnpm/9.15.0/dist/node_modules/node-gyp/lib/find-python.js:164:17)
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! stack at async configure (/root/.cache/node/corepack/v1/pnpm/9.15.0/dist/node_modules/node-gyp/lib/configure.js:27:18)
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! stack at async run (/root/.cache/node/corepack/v1/pnpm/9.15.0/dist/node_modules/node-gyp/bin/node-gyp.js:81:18)
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! System Linux 6.5.11-linuxkit
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! command "/usr/local/bin/node" "/root/.cache/node/corepack/v1/pnpm/9.15.0/dist/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=/app/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/app/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/build/Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v115"
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! cwd /app/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! node -v v20.18.1
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! node-gyp -v v10.2.0
150.4 .../canvas@2.11.2/node_modules/canvas install: gyp ERR! not ok 
150.5 .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! build error 
150.5 .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /root/.cache/node/corepack/v1/pnpm/9.15.0/dist/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/app/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/app/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1)
150.5 .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/app/node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
150.5 .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
150.5 .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1104:16)
150.5 .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
150.5 .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! System Linux 6.5.11-linuxkit
150.5 .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! command "/usr/local/bin/node" "/app/node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
150.5 .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! cwd /app/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas
150.5 .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! node -v v20.18.1
150.5 .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! node-pre-gyp -v v1.0.11
150.5 .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! not ok 
150.5 .../canvas@2.11.2/node_modules/canvas install: Failed to execute '/usr/local/bin/node /root/.cache/node/corepack/v1/pnpm/9.15.0/dist/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/app/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/app/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1)
150.5 .../canvas@2.11.2/node_modules/canvas install: Failed
193.8 .../node_modules/puppeteer postinstall: Error: ERROR: Failed to set up chrome-headless-shell v126.0.6478.126! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
193.8 .../node_modules/puppeteer postinstall:     at file:///app/node_modules/.pnpm/puppeteer@22.12.1_typescript@5.4.5/node_modules/puppeteer/lib/esm/puppeteer/node/install.js:84:27
193.8 .../node_modules/puppeteer postinstall:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
193.8 .../node_modules/puppeteer postinstall:     at async Promise.all (index 1)
193.8 .../node_modules/puppeteer postinstall:     at async downloadBrowser (file:///app/node_modules/.pnpm/puppeteer@22.12.1_typescript@5.4.5/node_modules/puppeteer/lib/esm/puppeteer/node/install.js:90:9) {
193.8 .../node_modules/puppeteer postinstall:   [cause]: Error: socket hang up
193.8 .../node_modules/puppeteer postinstall:       at TLSSocket.socketOnEnd (node:_http_client:528:25)
193.8 .../node_modules/puppeteer postinstall:       at TLSSocket.emit (node:events:530:35)
193.8 .../node_modules/puppeteer postinstall:       at endReadableNT (node:internal/streams/readable:1698:12)
193.8 .../node_modules/puppeteer postinstall:       at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
193.8 .../node_modules/puppeteer postinstall:     code: 'ECONNRESET'
193.8 .../node_modules/puppeteer postinstall:   }
193.8 .../node_modules/puppeteer postinstall: }
193.8 .../node_modules/puppeteer postinstall: Failed
193.8  ELIFECYCLE  Command failed with exit code 1.
------
failed to solve: process "/bin/sh -c pnpm install --prod --frozen-lockfile" did not complete successfully: exit code: 1`

**Comment by saidharanidhar** [comment]
No. It's still the same.

**Comment by myusuf3** [comment]
Same here. Really annoying when projects claim to be self hostable and they aren't.

**Comment by saidharanidhar** [comment]
Hi @ericciarla ,
I really appreciate all the work you and the team have done on this project! I wanted to follow up on this to see if there’s any update or anything we can do to help move it forward.

Please let me know if you need any additional details or if there's anything I can contribute to assist. Thanks in advance! 🙌

**Comment by ttli3** [comment]
not sure if anyone is still following this thread but I was able to fix by re-cloning latest version and then following fix in Issue #1103 [https://github.com/mendableai/firecrawl/issues/1103](url)

**Comment by busaud** [comment]
I have a fork of firecrawl that I haven't touched for 3 months. It used to be working last month but now I am getting this error when I try to build/rebuild. Maybe the issue is not with Firecrawl but some dependencies?

**Comment by busaud** [comment]
> > I pulled the latest code from main and it's still failing. The same error. Anything I have to change?
> 
> I modify the Dockerfile and add COREPACK_NPM_REGISTRY to Dockerfile‘s environment variables

Could you please elaborate more?

**Comment by zcoderr** [comment]
I encountered the same issue when using .env.local incorrectly as an environment variable. The [documentation](https://github.com/mendableai/firecrawl/blob/main/CONTRIBUTING.md) suggests copying .env.local for the environment variables. try it.

**Comment by saidharanidhar** [comment]
Hi @mogery ,

I hope this message finds you well. We're currently working with your docker image but facing some architecture compatibility challenges with our aarch64 environment.

Would it be possible for you to provide an aarch64-compatible version of your docker image? This would be tremendously helpful for our deployment and would allow us to fully leverage our current infrastructure.

Unfortunately, we're not able to build the image ourselves due to the above problems. Your expertise with this image would be invaluable in helping us move forward with our project.

We greatly appreciate your consideration and any assistance you can provide.
Thank you in advance

**Comment by mogery** [comment]
Hi @saidharanidhar! We'll be working on transitioning our own infrastructure to ARM as well, so this is planned in the near future.

**Comment by Morriz** [comment]
Any updates here?

**Comment by coryvirok** [comment]
Was able to get this working by using the gchr.io image and adding the platform attribute. Note: I'm on macos arm64 (Apple M1 Pro)

```diff
-  # image: ghcr.io/firecrawl/firecrawl
-  build: apps/api
+  image: ghcr.io/firecrawl/firecrawl
+  platform: linux/amd64
+  # build: apps/api
```

**Comment by limegreenpeper1** [comment]
It only runs after editing the two files.  Note: I'm on macos arm64 and podman.

1. set PORT=3000 on ./app/playwright-service/Dockerfile
before ----
ENV PORT=${PORT}
after ----
ENV PORT=3000

2. modify firecrawl newtorks on  ./docker-compose.yaml
before ----
networks:
  -backend
extra_hosts:
 -"host.docker.internal:host-gateway"
after : -----  add 1 row and remove 2 row
  networks:
    -backend
    -default

**Comment by Chadha93** [comment]
This is no longer an issue, it builds successfully locally (self-host), tested on Arm64 (M1)

@limegreenpeper1, if you are still facing this, you can simply uncomment the `#image: ghcr.io/firecrawl/firecrawl` in docker-compose.yml
